name: FlorisBoard nightly CI

on:
  schedule:
    - cron: '0 5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'florisboard/florisboard'
          submodules: recursive

      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle
      - name: Set up CMake and Ninja
        uses: lukka/get-cmake@latest
      - name: Build with Gradle
        # MUST call gradlew separately because of an OSS license plugin issue.
        # See https://github.com/google/play-services-plugins/issues/199
        run: ./gradlew clean && ./gradlew assembleBeta && mv app/build/outputs/apk/beta/app-beta.apk app/build/outputs/apk/beta/app-nightly.apk
      - uses: actions/upload-artifact@v3
        with:
          name: app-nightly.apk
          path: app/build/outputs/apk/beta/app-nightly.apk
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Nightly Build"
          files: |
            app/build/outputs/apk/beta/app-beta.apk
